app:
  remote_server_endpoint: [YourRemoteServerEndpoint]
  remote_server_requestor_ref: [YourRemoteServerRequestorRef]
  landing_enabled: true
  admin_enabled: false
  caching_enabled: false
  datalog_enabled: false
landing:
  title: DemoStopMonitorInstance
  logo: /static/default/logo.svg
  color: '#21a635'
  default_template: 'default'
  title_enabled: true
  num_results_enabled: false
  template_enabled: false
admin:
  something: ComesHereSoon
caching:
  caching_server_endpoint: [YourCachingServerEndpoint]
  caching_server_ttl_seconds: 30