name: Docker Image Tag CI
on:
  push:
    tags:
      - '*'
  workflow_dispatch: # allow manual start

jobs:
  docker-build-push-latest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repository
        uses: actions/checkout@v4
      - name: extract-tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: docker-login
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: docker-build-push
        run: |
          docker build -t sebastianknopf/stopmonitor:${{ env.TAG }} .
          docker push sebastianknopf/stopmonitor:${{ env.TAG }}
